### ISSUE TITLE
Can't upload images

### ISSUE THREAD

**Issue by vanten-s** [explodingcamera/docker-pleroma#1]
I can't upload a pfp/banner.

Logs:
```
pleroma_web  | Request: PATCH /api/v1/accounts/update_credentials
pleroma_web  | ** (exit) an exception was raised:
pleroma_web  |     ** (File.CopyError) could not copy from "/tmp/plug-1697/multipart-1697719071-816147301940269-4" to "/data/uploads/d2544bf9a13bd4fcf28846e09285233562b0854211b64da2fc0e5907b2fc4bd7.png": no such file or directory
pleroma_web  |         (elixir 1.14.5) lib/file.ex:838: File.cp!/3
pleroma_web  |         (pleroma 2.5.5) lib/pleroma/uploaders/local.ex:29: Pleroma.Uploaders.Local.put_file/1
pleroma_web  |         (pleroma 2.5.5) lib/pleroma/uploaders/uploader.ex:51: Pleroma.Uploaders.Uploader.put_file/2
pleroma_web  |         (pleroma 2.5.5) lib/pleroma/upload.ex:100: Pleroma.Upload.store/2
pleroma_web  |         (pleroma 2.5.5) lib/pleroma/web/activity_pub/activity_pub.ex:1456: Pleroma.Web.ActivityPub.ActivityPub.upload/2
pleroma_web  |         (pleroma 2.5.5) lib/pleroma/user.ex:661: Pleroma.User.put_upload/2
pleroma_web  |         (pleroma 2.5.5) lib/pleroma/user.ex:646: Pleroma.User.put_change_if_present/3
pleroma_web  |         (pleroma 2.5.5) lib/pleroma/user.ex:589: Pleroma.User.update_changeset/2
```

**Comment by vanten-s** [comment]
My bad, forgot upload folder
